backend:
  name: github
  repo: rpreetk89/finds-radar
  branch: main
  base_url: https://still-mouse-cffe.rpreetk-89.workers.dev
  auth_endpoint: auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Product Inventory"
    files:
      - file: "_data/products.json"
        label: "Product Inventory List"
        name: "products_file"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Affiliate Link", name: "affiliate_link", widget: "string" }
              - { label: "Category", name: "category", widget: "string" }
              - { label: "Media Gallery", name: "media", widget: "list", fields: [
                  { label: "Type", name: "type", widget: "select", options: ["image", "video"] },
                  { label: "URL", name: "url", widget: "string" }
                ]}